### ISSUE TITLE
No known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'

### ISSUE THREAD

**Issue by BurapaLi** [qxuewei/XWDatabase#2]
data = [NSKeyedArchiver archivedDataWithRootObject:customModel requiringSecureCoding:YES error:nil];
报错 ：No known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'

**Comment by BurapaLi** [comment]
No known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'

**Comment by qxuewei** [comment]
您的手机设备是什么系统？可以将您报错的Demo 发到这个邮箱 qxuewei@yeah.net  谢谢！

**Comment by BurapaLi** [comment]
> 您的手机设备是什么系统？可以将您报错的Demo 发到这个邮箱 [qxuewei@yeah.net](mailto:qxuewei@yeah.net) 谢谢！

clone 下来 demo直接报错在那

**Comment by qxuewei** [comment]
代码里我已经判断了只有满足 iOS11 + 的系统才执行 'archivedDataWithRootObject:requiringSecureCoding:error:' 方法，而且我在各个版本的模拟器上运行Demo 都没发现您说的问题。iOS12 的真机也没您说的问题。您也可以帮忙分析一下原因，我会持续跟进，谢谢

**Comment by BurapaLi** [comment]
> 代码里我已经判断了只有满足 iOS11 + 的系统才执行 'archivedDataWithRootObject:requiringSecureCoding:error:' 方法，而且我在各个版本的模拟器上运行Demo 都没发现您说的问题。iOS12 的真机也没您说的问题。您也可以帮忙分析一下原因，我会持续跟进，谢谢

习惯了用低版本xcode打开，用高版本打开就没问题了

**Comment by qxuewei** [comment]
感谢您的反馈😊
