### ISSUE TITLE
no such column

### ISSUE THREAD

**Issue by milletpeak** [qxuewei/XWDatabase#3]
![CD6AB0BA-522C-4BF1-9056-68F4C1BA60F2](https://user-images.githubusercontent.com/20568661/55380284-54ce5b80-5552-11e9-8d93-3e19b6472a40.png)  这个错误您知道怎么回事吗，根据用户名的id存储 调用[XWDatabase saveModel:messageListModel identifier:[LZLoginData memberId] completion:];

**Comment by milletpeak** [comment]
老是说no such column ：。。。

[XWDatabase getModels:LZMessageListModel.class identifier:[LZLoginData memberId] completion:^(NSArray * _Nullable objs) {
            NSLog(@"arrays = %@",objs);

            NSMutableArray <LZMessageListModel *> *arrays = [[NSMutableArray alloc] initWithArray:objs];
            //数据为空
            if (arrays.count == 0) {
                /// 保存无主键模型 (指定用户)
                [arrays addObject:messageListModel];
                //保存数据
                [XWDatabase saveModels:arrays identifier:[LZLoginData memberId] completion:^(BOOL isSuccess) {
                    NSLog(@" <XWDatabase> saveModel (%@)",isSuccess?@"成功":@"失败");
                }];
                
            }else{
                
                [arrays addObject:messageListModel];
                //数据不为空，更新数据
                [XWDatabase updateModels:arrays identifier:[LZLoginData memberId] updatePropertys:@[] completion:^(BOOL isSuccess) {
                    NSLog(@" <XWDatabase> updateModels (%@)",isSuccess?@"成功":@"失败");
                }];
            }
            
        }];

**Comment by qxuewei** [comment]
如果模型的数据结构有变化在 模型的 load 方法里实现  [XWDatabase updateTable] 方法

**Comment by milletpeak** [comment]
已经实现了，还是会出现这个错误，搞不懂

**Comment by qxuewei** [comment]
Demo 发我 732087079

**Comment by milletpeak** [comment]
我发现saveModels:identifier这个identifier这个值不能出现英文字母，一出现就会保存失败 
[XWDatabase saveModels:arrays identifier:[LZLoginData memberId] completion:^(BOOL isSuccess) {
                NSLog(@" <XWDatabase> saveModel (%@)",isSuccess?@"成功":@"失败"); }];
保存成功，我后面想给saveModels的数组中再追加数据怎么加？

**Comment by qxuewei** [comment]
英文字母的问题我再下个版本修复一下，感谢您的反馈。追加数据对新增的数组调用 [XWDatabase saveModels] 方法就可以把新数据继续添加到数据库中的

**Comment by lztbwlkj** [comment]
我使用saveModel添加 添加到是成功了，但是数据出现了重复添加的情况，我明明添加了2条但是读取出来的数据不止两条，要删除以前存的数据再追加吗？

**Comment by milletpeak** [comment]
[MSDB.zip](https://github.com/qxuewei/XWDatabase/files/3036585/MSDB.zip) 你的qq我加不上 你加我的903607388

**Comment by qxuewei** [comment]
如果保存的模型里有自定义对象需要对自定义对象进行归解档操作！ 升级一下使用1.1.1 版本。你的 demo 我给你改造了一下，有什么问题随时留言！为了你我加班了三个小时！
[Uploading MSDB 2.zip…](MSDB2)

**Comment by qxuewei** [comment]
如果保存的模型里有自定义对象需要对自定义对象进行归解档操作！ 升级一下使用1.1.1 版本。你的 demo 我给你改造了一下，有什么问题随时留言！为了你我加班了三个小时！
[MSDB 2.zip](https://github.com/qxuewei/XWDatabase/files/3038955/MSDB.2.zip)
