### ISSUE TITLE
通过identifier保存之后不能查找到数据

### ISSUE THREAD

**Issue by yexiwen** [qxuewei/XWDatabase#5]
通过identifier保存之后不能查找到数据
XWDatabaseSQL.m 中identifierValue设置有问题
+ (NSString *)searchSql:(Class<XWDatabaseModelProtocol>)cls identifier:(NSString * _Nullable)identifier sortColumn:(NSString *)sortColumn isOrderDesc:(BOOL)isOrderDesc condition:(NSString *)condition limitCount:(NSUInteger)limitCount

//    NSString *identifierValue = (identifier ? identifier : [NSString stringWithFormat:@"'%@'",kXWDB_IDENTIFIER_VALUE]);
改为
      NSString *identifierValue = (identifier ? [NSString stringWithFormat:@"'%@'",identifier] : [NSString stringWithFormat:@"'%@'",kXWDB_IDENTIFIER_VALUE]) ;

**Comment by qxuewei** [comment]
可以，下个版本加上这个优化。
