### ISSUE TITLE
model 里面有一个字段是数组  现在想判断一个元素是否在这个字段数组里面，可以实现吗 ？怎么写？

### ISSUE THREAD

**Issue by LAnqxpp** [qxuewei/XWDatabase#6]

**Comment by LAnqxpp** [comment]
已经试过 sql   SELECT * FROM A a WHERE a.aa like '1%,' or a.aa like '%,1,%'

**Comment by qxuewei** [comment]
> 已经试过 sql SELECT * FROM A a WHERE a.aa like '1%,' or a.aa like '%,1,%'

只能通过主键把这个 model 取出来，自行判断
