### ISSUE TITLE
XWDatabase :Invalid type in JSON write (UIImage)

### ISSUE THREAD

**Issue by alphaLogin** [qxuewei/XWDatabase#7]
写了一个ary，里面放的是uiimage ，就引申出来这个问题：Invalid type in JSON write (UIImage)

**Comment by qxuewei** [comment]
把uiimage作为对象model的一个属性存储下试试呢，存对象而不是直接存 UIimage 数组

**Comment by alphaLogin** [comment]
这个需求是一开始就确立的，因为这个是从图库里面选择的，返回的数量是不确定的。
不过这个问题已经解决～～
网上查了下,能够转换为json字符串的对象必须具有如下属性:
顶层对象必须是NSArray或者NSDictionary；
所有的对象必须是NSString/NSNumber/NSArray/NSDictionary/NSNull的实例；
所有NSDictionary的key必须是NSString类型；
数字对象不能是非数值或无穷;

所以这里我在存取的时候用base64 ，decode和encode。
最后感谢您的回复～
